In [1]:
import torch
print(torch.__version__)

2.6.0+cpu


In [ ]:
print(torch.cuda.is_available())

False


In [23]:
a = torch.empty(2, 3)
print(a.shape[0])

2


In [5]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.rand(2, 4)

tensor([[0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876]])

In [12]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [22]:
print(torch.tensor([[1,2,3], [4,5,6]]))
# print(torch.linspace, torch.arange, torch.eye)
print(torch.full((2, 5) ,3))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]])


In [32]:
mat = torch.tensor([[1,3],[4,5]])
mat = mat.float()
print(torch.det(mat))
mat = torch.tensor([[1,3],[4,5]], dtype=torch.float)
print(torch.det(mat))


tensor(-7.)
tensor(-7.)


In [33]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])
tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])


In [34]:
m+n

tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])

In [35]:
m.add_(n)
m

tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])