In [11]:
import torch.nn as nn


class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        return self.sigmoid(self.linear(features))
        
    # def forward1(self, features):
    #     return self.sigmoid(self.linear(features) * 2)


In [12]:
# PyTorch’s __call__ Mechanism: When you call model(features), PyTorch’s nn.Module.__call__ method looks for a 
# method named forward in your class to execute the forward pass. It does not look for forward1 or any other method.

# Missing forward Method: If the forward method is not defined, PyTorch 
# cannot find it, and you’ll get an AttributeError like the one above.

# Explicit forward1 Call: Calling model.forward1(features) works because it’s just a regular 
# method call, and forward1 exists in your class. However, it’s not tied to PyTorch’s __call__ 
# mechanism, so it doesn’t benefit from features like hooks or mode handling.

In [13]:
import torch


features = torch.rand(10, 5)
model = Model(features.shape[1])
# model.forward(features)
model(features) 	        # prefer this method

tensor([[0.4339],
        [0.4454],
        [0.4361],
        [0.4234],
        [0.4637],
        [0.4581],
        [0.5004],
        [0.4250],
        [0.3825],
        [0.4250]], grad_fn=<SigmoidBackward0>)

In [16]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[-0.0368, -0.2205, -0.2299, -0.2194, -0.3038]], requires_grad=True),
 Parameter containing:
 tensor([0.2656], requires_grad=True))

In [17]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00