In [7]:
# import torch.nn as nn


# class Model(nn.Module):
#     def __init__(self, num_features):
#         super().__init__()
#         self.linear1 = nn.Linear(num_features, 3)
#         self.relu = nn.ReLU()
#         self.linear2 = nn.Linear(3, 1)
#         self.sigmoid = nn.Sigmoid()

#     def forward(self, features):
#         return self.sigmoid(self.linear2(self.relu(self.linear1(features))))

import torch.nn as nn


class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        return self.network(features)

In [8]:
import torch


features = torch.rand(10, 5)

model = Model(features.shape[1])
model(features)

tensor([[0.4388],
        [0.4394],
        [0.4340],
        [0.4410],
        [0.4375],
        [0.4356],
        [0.4286],
        [0.4286],
        [0.4314],
        [0.4387]], grad_fn=<SigmoidBackward0>)

In [ ]:
# model.linear1.weight, model.linear1.bias, model.linear2.weight, model.linear2.bias

(Parameter containing:
 tensor([[-0.2739, -0.3399,  0.0110, -0.2366,  0.2039],
         [-0.4260,  0.2939,  0.4158,  0.3096, -0.1127],
         [-0.0049, -0.2293,  0.2010, -0.3593,  0.4024]], requires_grad=True),
 Parameter containing:
 tensor([-0.1009,  0.4108,  0.3987], requires_grad=True),
 Parameter containing:
 tensor([[-0.0402,  0.1709,  0.2625]], requires_grad=True),
 Parameter containing:
 tensor([0.3930], requires_grad=True))

In [9]:
from torchinfo import summary


summary(model, input_size=(10 ,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00