In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

array([[ 1.14088912,  0.29119144,  1.1393575 , ...,  0.53470127,
         0.28374015, -0.3071591 ],
       [-0.72497441, -0.06420089, -0.7325317 , ..., -0.74268822,
         0.22100066, -0.08127578],
       [ 0.43219318,  0.21503594,  0.40827631, ...,  0.48776069,
         1.76213973,  1.18281237],
       ...,
       [ 1.26823292,  0.48734954,  1.22371302, ...,  1.34934749,
         1.25700646,  0.7696766 ],
       [ 0.44049821,  0.82889542,  0.53280113, ...,  1.32814852,
         0.60548108,  2.19150749],
       [-0.17961074, -1.14422432, -0.19988683, ...,  0.19854615,
         0.12769579, -0.63122924]])

In [5]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,

In [7]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32)) # type: ignore
y_test_tensor = torch.from_numpy(y_test.astype(np.float32)) # type: ignore

X_train_tensor.shape, y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

In [8]:
from torch.utils.data import DataLoader, Dataset


class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)
    
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [9]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

train_dataset[10]

(tensor([ 1.2821,  0.6120,  1.2558,  1.2265,  0.3648,  0.6304,  0.8848,  0.9665,
          0.4558, -0.2240,  1.4013,  1.2981,  0.7424,  1.2774,  0.3004,  0.8432,
          0.9326,  1.1393,  0.4035,  0.2817,  1.2618,  0.8210,  1.0728,  1.1879,
          0.2608,  0.5454,  0.5663,  0.8345,  0.1760, -0.0652]),
 tensor(1.))

In [10]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [11]:
import torch.nn as nn


class NN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        return self.sigmoid(self.linear(features))

In [12]:
learning_rate = 0.1
epochs = 25

In [13]:
model = NN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
loss_fn = nn.BCELoss()

In [17]:
for epoch in range(epochs):
    for batch_features, batch_labels in train_loader:
        y_pred = model(batch_features)
        loss = loss_fn(y_pred, batch_labels.view(-1, 1))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.05499815195798874
Epoch: 2, Loss: 0.029503628611564636
Epoch: 3, Loss: 0.033797696232795715
Epoch: 4, Loss: 0.0007414681022055447
Epoch: 5, Loss: 0.07158924639225006
Epoch: 6, Loss: 0.4170364737510681
Epoch: 7, Loss: 0.03398852422833443
Epoch: 8, Loss: 0.0013633474009111524
Epoch: 9, Loss: 0.35917991399765015
Epoch: 10, Loss: 0.027726007625460625
Epoch: 11, Loss: 0.09307636320590973
Epoch: 12, Loss: 0.08697128295898438
Epoch: 13, Loss: 0.027663320302963257
Epoch: 14, Loss: 0.0016791720408946276
Epoch: 15, Loss: 0.08374657481908798
Epoch: 16, Loss: 0.03994454815983772
Epoch: 17, Loss: 0.01472485065460205
Epoch: 18, Loss: 0.07436070591211319
Epoch: 19, Loss: 0.07454761117696762
Epoch: 20, Loss: 0.004223496187478304
Epoch: 21, Loss: 0.023180456832051277
Epoch: 22, Loss: 0.00031358315027318895
Epoch: 23, Loss: 0.002520789857953787
Epoch: 24, Loss: 0.005937532987445593
Epoch: 25, Loss: 0.02197127975523472


In [19]:
model.eval()
accuracy = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()
        batch_accuracy = (y_pred.view(-1, 1) == batch_labels).float().mean()
        accuracy.append(batch_accuracy)

print(f"Test accuracy: {sum(accuracy)/len(accuracy)}")

Test accuracy: 0.5717592239379883
